version: '3.3'
services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_PASSWORD: postgrespassword
    ports:
     - 5432:5432
    volumes:
     - db_data:/var/lib/postgresql/data
    networks:
     - swarmpit_net
    logging:
      driver: json-file
networks:
  swarmpit_net:
    driver: overlay
volumes:
  db_data:
    driver: local
