version: '3.3'
services:
  api-standardization:
    image: api-standardization:latest
    environment:
      HASURA_SECRET: perc
      HASURA_URL: http://192.168.100.46:8090/v1/graphql
    ports:
     - 8082:8082
    networks:
     - swarmpit_net
    logging:
      driver: json-file
networks:
  swarmpit_net:
    driver: overlay
